################################################

# This is GLOBAL define to make the integration easier.
def-y += DISABLE_MCAL_INTERMODULE_ASR_CHECK

MCAL_PLUGINS_PATH=../MCAL/plugins
MCAL_VERSION=T40D2M10I2R0
MCAL_CONFIG_PATH=../MCAL

# Confguration generated by NXP MCAL
inc-y += $(MCAL_CONFIG_PATH)/generated/include
vpath-y += $(MCAL_CONFIG_PATH)/generated/src

################################################
# Special ARCCORE integration files
ifeq ($(USE_ARC),y)
ARC-MOD-MK=$(MCAL_CONFIG_PATH)/arc.mod.mk
include $(ARC-MOD-MK)
endif

# Override default Arccore MCU
ifeq ($(USE_MCU),y)
MCU-MOD-MK=$(MCAL_CONFIG_PATH)/mcu.mod.mk
endif

ifeq ($(USE_PORT),y)
PORT-MOD-MK=$(MCAL_CONFIG_PATH)/port.mod.mk
endif

ifeq ($(USE_CAN),y)
CAN-MOD-MK=$(MCAL_CONFIG_PATH)/can.mod.mk
endif

ifeq ($(USE_DIO),y)
DIO-MOD-MK=$(MCAL_CONFIG_PATH)/dio.mod.mk
endif

ifeq ($(USE_ADC),y)
ADC-MOD-MK=$(MCAL_CONFIG_PATH)/adc.mod.mk
endif

ifeq ($(USE_FLS),y)
FLS-MOD-MK=$(MCAL_CONFIG_PATH)/fls.mod.mk
endif

ifeq ($(USE_PWM),y)
PWM-MOD-MK=$(MCAL_CONFIG_PATH)/pwm.mod.mk
endif

ifeq ($(USE_WDG),y)
WDG-MOD-MK=$(MCAL_CONFIG_PATH)/wdg.mod.mk
endif

ifeq ($(USE_GPT),y)
GPT-MOD-MK=$(MCAL_CONFIG_PATH)/gpt.mod.mk
include $(GPT-MOD-MK)
endif

ifeq ($(USE_MCALBASE),y)
MCALBASE-MOD-MK=$(MCAL_CONFIG_PATH)/base.mod.mk
include $(MCALBASE-MOD-MK)
endif

ifeq ($(USE_MCL),y)
MCL-MOD-MK=$(MCAL_CONFIG_PATH)/mcl.mod.mk
include $(MCL-MOD-MK)
endif

