/*
 * SchM_Wdg.h
 *
 *  Created on: 03-Mar-2017
 *      Author: sina
 */

#ifndef SCHM_WDG_H_
#define SCHM_WDG_H_

#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_00() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_01() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_02() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_03() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_04() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_05() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_06() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_07() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_08() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_09() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_10() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_11() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_12() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_13() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_14() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_15() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_16() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_17() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_18() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_19() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_20() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_21() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_22() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_23() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_24() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_25() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_26() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_27() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_28() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_29() SuspendOSInterrupts()
#define SchM_Enter_Wdg_WDG_EXCLUSIVE_AREA_30() SuspendOSInterrupts()

#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_00() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_01() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_02() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_03() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_04() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_05() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_06() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_07() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_08() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_09() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_10() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_11() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_12() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_13() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_14() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_15() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_16() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_17() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_18() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_19() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_20() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_21() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_22() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_23() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_24() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_25() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_26() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_27() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_28() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_29() ResumeOSInterrupts()
#define SchM_Exit_Wdg_WDG_EXCLUSIVE_AREA_30() ResumeOSInterrupts()

#endif /* SCHM_WDG_H_ */
